[package]
name = "actix_htmx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.1"
actix-files = "0.6.2"
actix-web = "4.4.1"
env_logger = "0.10.1"
log = "0.4.20"
tera = "1.19.1"
